runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest
- name: flask
  version: latest
- name: jinja2
  version: latest
- name: six
  version: latest